apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-housekeeper-deployment
  labels:
    app: housekeeper
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: housekeeper
  template:
    metadata:
      labels:
        app: housekeeper
    spec:
      containers:
        - name: housekeeper
          image: {{ .Values.global.aws_account }}.dkr.ecr.{{ .Values.global.aws_default_region }}.amazonaws.com/{{ .Values.global.app_name }}-{{ .Values.global.deploy_dev }}-backend:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          args: 
            - start-housekeeper
          resources:
              requests:
                cpu: {{ .Values.resources.cpu }}
          env: 
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.global.aws_default_region }}
            - name: API_RUN_LOCATION
              value: k8s
            - name: DOMAIN_NAME
              value: {{ .Values.global.ingress.hostname }}
      nodeSelector:
        node-pool: {{ .Values.global.node_selector }} 

