---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.service_account_name }}_role
rules:
- apiGroups: ["*"]
  resources: ["pods", "services"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.service_account_name }}_rolebinding
subjects:
- kind: ServiceAccount
  namespace: nm
  name: default
roleRef:
  kind: Role
  name: {{ .Values.service_account_name }}_role
  apiGroup: rbac.authorization.k8s.io
